# NetOffice project build pipeline

pool:
  vmImage: 'windows-2019'

variables:
  solution: Source/NetOffice.sln
  buildPlatform: Any CPU
  buildConfiguration: Release

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1 SDK'
  inputs:
    packageType: sdk
    version: 3.1.102

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)\Source'
    contents: '**' 
    targetFolder: '$(Build.ArtifactStagingDirectory)\Source'

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '5.4.0'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build NetOffice
  inputs:
    solution: '$(solution)'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Build;Pack /p:RepositoryBranch="$(Build.SourceBranchName)" /p:RepositoryCommit="$(Build.SourceVersion)" /p:PackageOutputPath="$(Build.ArtifactStagingDirectory)"'
    createLogFile: true
    logFileVerbosity: 'detailed'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      Source\NetOffice.Tests\bin\**\NetOffice.Tests.dll

- task: DeleteFiles@1
  displayName: Cleanup assemblies output
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)\Source\ClientApplication\bin\$(buildConfiguration)'
    contents: |
      'ClientApplication.*'
      'stdole.dll'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)\Source\ClientApplication\bin\$(buildConfiguration)'
    contents: '**' 
    targetFolder: '$(Build.ArtifactStagingDirectory)\Assemblies\Any CPU'

- task: ArchiveFiles@2
  displayName: Create NetOffice Package
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/NetOffice_unsigned_build$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/NetOffice_unsigned_build$(Build.BuildId).zip'
    artifactName: NetOffice Package
