# NetOffice project build pipeline

pool:
  vmImage: 'windows-2019'

variables:
  solution: Source/NetOffice.sln
  buildPlatform: Any CPU
  buildConfiguration: Debug
  VersionSuffix: 'alpha-$(Build.BuildId)'
  BuildNumber: $(Build.BuildId)

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Build;Pack /p:VersionSuffix="$(VersionSuffix)" /p:BuildNumber="$(BuildNumber)"'
    createLogFile: true
    logFileVerbosity: 'detailed'

- publish: 'artifacts'
  artifact: 'NetOffice packages'
