# NetOffice project build pipeline

pool:
  vmImage: 'windows-2019'

variables:
  solution: Source/NetOffice.sln
  buildPlatform: Any CPU
  buildConfiguration: Debug
  VersionSuffix: 'alpha-$(Build.BuildId)'
  BuildNumber: $(Build.BuildId)

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build NetOffice
  inputs:
    solution: '$(solution)'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Build;Pack /p:VersionSuffix="$(VersionSuffix)" /p:BuildNumber="$(BuildNumber)"'
    createLogFile: true
    logFileVerbosity: 'detailed'

- task: PublishBuildArtifacts@1
  displayName: Publish NetOffice artifacts
  inputs:
    pathtoPublish: 'artifacts'
    artifactName: 'NetOffice packages'

- task: NuGetCommand@2
  displayName: Push NetOffice packages to MyGet.org
  inputs:
    command: push
    packagesToPush: 'artifacts/**/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'MyGet NetOffice feed'
